### ISSUE TITLE
Space usage

### ISSUE THREAD

**Issue by sheganinans** [mgajda/json-autotype#10]
Hello! Excellent package you've built here! I'm trying to run your program over some rather large (50GB) JSON files, as you can guess, it eats up all the RAM on my computer and it freezes. I was wondering where the low hanging fruit are in terms of remedying this problem. Any thoughts of switching this package to conduit or something similar to have constant space streaming? Maybe some kind of map-reduce like job chunking and saving intermediate results on disk to flush RAM and then a final merge at the end to give a final result?

**Comment by mgajda** [comment]
We currently use Aeson library, and this is the main reason for the space consumption, since types are usually much smaller than the data.
To amend this we would have to produce parser using some conduit-based JSON parsing package.
Unfortunately this does not seem to be the dominant solution, so support would be flaky (There is `ndjson-conduit`, but it seems to have limitations.)

For the time being, I can ameliorate the issue by forcing strict parsing (and thus decreasing time spent, since entire input is inspected.)

**Comment by mgajda** [comment]
PS Can you provide pointers to concrete test cases?

**Comment by sheganinans** [comment]
Makes sense. The concrete case I'm dealing with here is the wikidata dump:
https://dumps.wikimedia.org/wikidatawiki/entities/ The bz2 file expands out
into a 50GB json file.

**Comment by mgajda** [comment]
Thanks for the example!
Do you have any suggestions as to how would you parse the JSON with conduit alone?

**Comment by sheganinans** [comment]
No problem! Surprisingly, I can't find a conduit library, but there is a pipes lib: https://hackage.haskell.org/package/pipes-aeson

Seems like this is an opportunity to patch a missing hole in the conduit ecosystem..

**Comment by sheganinans** [comment]
Here are some related libs that might be hooked into aeson or some other parser to lift them into a conduit:

https://github.com/k0ral/conduit-parse
https://hackage.haskell.org/package/conduit-extra-1.1.10.1/docs/Data-Conduit-Attoparsec.html
https://hackage.haskell.org/package/cereal-conduit

**Comment by sheganinans** [comment]
Ok, just whirred a big AWS instance and ran json-autotype on the wikidata. Basically the data usage is a bit more and double the input data. The latest dump is 64GB and it used about 140GB at it's peak.

**Comment by sheganinans** [comment]
Strange, for some reason it does not output the generated file.. Know what might be the cause? Here's the command I'm using:

```bash
json-autotype latest-all.json -o WikiData.hs
```

**Comment by sheganinans** [comment]
Wow, even without switching over to conduit, there seems to be some low hanging fruit that can be fixed. I just whirred up an AWS instance with 240GB of RAM and my 64GB file ate it all up. Soon enough there will be the 2TB instances available, but they aren't out yet. Point being, I think you make have some space leaks from excessive laziness. I think it might be a good idea to add some strictness annotations in the places you think it would help.

**Comment by sheganinans** [comment]
Well, I just tried some really naive additions of strictness annotations. Didn't really help the picture..

**Comment by mgajda** [comment]
It is clear that the only (and the right) way to decrease memory usage is to change into a streaming parser. Such a streaming parser could then perform unification of array elements online.

While it does not change functionality of the program, it would be a major development effort.
I may mentor anybody interested in doing it on their own time and budget, but I do not have immediate need to improve this at the moment.

Thus I close this as suggestion for possible improvement, but not very important one.

These are possible workarounds:
1. Use streaming JSON parser to subdivide top array into files, and give input to JSON-Autotype as multiple files on the same command line. (Each file with just single element, or few elements.) Can be easily used to decrease file size 100x, and thus satisfy the need.
2. If JSON was produced by Web API or database, we might use queries of narrower scope, and again give multiple results as separate files on command line.

These are alternative ways to address this problem in a context of big datasets:
A. Use library interface to derive types for objects one-by-one, and then unify them. That can be also in parallel. I will mentor the effort for deriving types from MongoDB, if there is a willing implementor.
B. Add an option to JSON-Autotype so that we can first produce JSON Schema that is the result, and another option to read JSON schema to prime inference.

I will close the ticket, until a willing implementor appears, or until there appears immediate need & budget for further work.

**Comment by mgajda** [comment]
Here I found two ways to implement streamed parsing for JSON:
http://hackage.haskell.org/package/json-stream

However neither funders, nor students shown interest so far...
